language: java
jdk: oraclejdk7
after_success:
- ./upload.sh
before_install:
- openssl aes-256-cbc -K $encrypted_c87112105917_key -iv $encrypted_c87112105917_iv
  -in secring.gpg.enc -out secring.gpg -d
